AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::658514554862:role/service-role/search-photos-role-fdb1iia9'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY

